import { SettingsFormField } from "@devvit/public-api";

export enum Setting {
    Action = "action",
    BanMessage = "banMessage",
    MinimumCommentCount = "minCommentCount",
    AutogenUsersOnly = "autogenUsersOnly",
    MaximumAgeMonths = "maximumAgeInMonths",
    MaxKarma = "maximumKarma",
    MaxCommentLength = "maxCommentLength",
    SubredditDiversity = "subredditDiversity",
}

export enum AIBotDetectionAction {
    None = "none",
    Report = "report",
    BanAndRemove = "banandremove",
}

export const settingsForAIBotDetection: SettingsFormField[] = [
    {
        name: Setting.Action,
        type: "select",
        label: "Action to take",
        options: [
            { label: "No action (disable)", value: AIBotDetectionAction.None },
            { label: "Report", value: AIBotDetectionAction.Report },
            { label: "Ban and Remove", value: AIBotDetectionAction.BanAndRemove },
        ],
        defaultValue: [AIBotDetectionAction.Report],
    },
    {
        name: Setting.BanMessage,
        type: "string",
        label: "Ban reason",
        defaultValue: "LLM Bot",
    },
    {
        name: Setting.MinimumCommentCount,
        type: "number",
        label: "Minimum comments on account to allow checking",
        helpText: "If this is set too low, false positives on new non-bot accounts will occur. Users will be re-checked every few hours.",
        defaultValue: 4,
    },
    {
        name: Setting.AutogenUsersOnly,
        type: "boolean",
        label: "Check comments of users with autogenerated usernames only",
        helpText: "Most LLM bot accounts seem to be autogen usernames only. Disabling this option will widen detection, but may have false positives.",
        defaultValue: true,
    },
    {
        name: Setting.MaximumAgeMonths,
        type: "number",
        label: "Maximum account age in months",
        helpText: "Most LLM bot accounts are relatively young. Keep this as low as possible to detect bots without false positives.",
        defaultValue: 3,
    },
    {
        name: Setting.MaxKarma,
        type: "number",
        label: "Maximum account comment karka",
        helpText: "Most LLM bot accounts are low karma. Keep this as low as possible to detect bots without false positives.",
        defaultValue: 500,
    },
    {
        name: Setting.MaxCommentLength,
        type: "number",
        label: "Maximum comment length",
        helpText: "Most LLM bot accounts leave short comments only. Keep this number as low as possible to avoid false positives",
        defaultValue: 500,
    },
    {
        name: Setting.SubredditDiversity,
        type: "number",
        label: "Ratio of comments to subreddits threshold",
        helpText: "Most LLM bot accounts comment on a wide range of subreddits. This figure is the number of comments divided by the number of distinct subreddits. If the user's figure is greater than this number, they won't be treated as a bot.",
        defaultValue: 2.5,
    },
];
